import "server-only"

import { analyzeSchema, type AnalysisError } from "@/lib/ast/analyzer"
import { validateASTShape } from "@/lib/ast/validator"
import { geminiProvider } from "@/lib/ai/providers/gemini"
import { createCompilerRegistry, CompilerId, type CompileAllResult } from "@/lib/compiler"
import { createGeneration } from "@/lib/repositories/generation.repository"
import { getProjectById } from "@/lib/repositories/project.repository"
import type { GeneratedSchema } from "@/types/schema"

// The public contract is unchanged from the legacy Gemini-direct-artifact
// pipeline: SUCCESS/GENERATED_NOT_SAVED still carry `data: GeneratedSchema`
// (the same sql/drizzle/json/documentation?/mermaidDiagram? shape the UI
// and the generations table have always used), so lib/actions/generate-schema.ts
// and features/ai-workspace/components/schema-generator.tsx need no
// changes. What's
// new is *how* that GeneratedSchema gets built — five distinct
// statuses (AI_ERROR, INVALID_AST, SEMANTIC_VALIDATION_FAILED,
// COMPILER_FAILED, GENERATED_NOT_SAVED) now separate the five ways the
// new pipeline can fail, where the old pipeline only had three.
export type GenerateAndPersistResult =
  | { status: "SUCCESS"; data: GeneratedSchema; generationId: string }
  | { status: "GENERATED_NOT_SAVED"; data: GeneratedSchema; error: string }
  | { status: "PROJECT_NOT_FOUND"; error: string }
  | { status: "AI_ERROR"; error: string }
  | { status: "INVALID_AST"; error: string }
  | { status: "SEMANTIC_VALIDATION_FAILED"; error: string }
  | { status: "COMPILER_FAILED"; error: string }

// Prompt -> GeminiProvider.generateAST() -> validateASTShape() ->
// analyzeSchema() -> createCompilerRegistry().compileAll() -> persist ->
// return. This replaces the old Prompt -> Gemini -> {sql, drizzle, json,
// docs, mermaid} pipeline: Gemini now only ever produces a
// CanonicalSchemaAST (lib/ai/providers/gemini.ts) — every artifact is
// compiled from it deterministically (lib/compiler), never generated by
// the model directly.
export async function generateAndPersistSchema(input: {
  prompt: string
  projectId: string
}): Promise<GenerateAndPersistResult> {
  // Ownership check happens before the (expensive) AI call, and produces
  // an explicit user-facing message rather than letting the eventual
  // persist step fail on an RLS/FK violation the caller can't interpret.
  const projectResult = await getProjectById(input.projectId)
  if (!projectResult.ok) {
    return { status: "PROJECT_NOT_FOUND", error: "Project not found." }
  }

  const generationResult = await geminiProvider.generateAST({ prompt: input.prompt })
  if (!generationResult.ok) {
    return { status: "AI_ERROR", error: generationResult.error }
  }

  const shapeResult = validateASTShape(generationResult.ast)
  if (!shapeResult.ok) {
    return {
      status: "INVALID_AST",
      error: "The AI produced a schema that doesn't match the expected structure. Please try again.",
    }
  }

  const analysis = analyzeSchema(shapeResult.data)
  if (!analysis.valid) {
    return {
      status: "SEMANTIC_VALIDATION_FAILED",
      error: summarizeAnalysisErrors(analysis.errors),
    }
  }

  const registry = createCompilerRegistry()
  const compiled = registry.compileAll(shapeResult.data)

  const artifactsResult = buildGeneratedArtifacts(compiled)
  if (!artifactsResult.ok) {
    return { status: "COMPILER_FAILED", error: artifactsResult.error }
  }

  const persistResult = await createGeneration({
    projectId: input.projectId,
    prompt: input.prompt,
    artifacts: artifactsResult.data,
  })

  if (!persistResult.ok) {
    return { status: "GENERATED_NOT_SAVED", data: artifactsResult.data, error: persistResult.error }
  }

  return { status: "SUCCESS", data: artifactsResult.data, generationId: persistResult.data.id }
}

function summarizeAnalysisErrors(errors: AnalysisError[]): string {
  return errors.map((error) => error.message).join(" ")
}

// Maps CompileAllResult[] onto the GeneratedSchema the UI/persistence
// layer already expects. sql/drizzle/json are required fields on
// GeneratedSchema, so a failure in any of those three compilers is a
// hard COMPILER_FAILED — there is no valid GeneratedSchema without them.
// documentation/mermaidDiagram are optional on GeneratedSchema (the
// original AI prompt's own rule was "omit rather than guess"), so a
// failure in either of those compilers degrades gracefully: the field is
// just left out, not treated as a pipeline failure.
//
// Exported (not just used internally) so this pure mapping step —
// arguably the highest-risk new logic in this file — can be exercised
// directly against a real compileAll() output without needing a live AI
// call or database connection.
export function buildGeneratedArtifacts(
  compiled: CompileAllResult[]
): { ok: true; data: GeneratedSchema } | { ok: false; error: string } {
  const byId = new Map(compiled.map((entry) => [entry.id, entry.result]))

  const sql = requireCompilerOutput(byId.get(CompilerId.PostgresSql), "SQL")
  if (!sql.ok) {
    return sql
  }

  const drizzle = requireCompilerOutput(byId.get(CompilerId.Drizzle), "Drizzle")
  if (!drizzle.ok) {
    return drizzle
  }

  const json = requireCompilerOutput(byId.get(CompilerId.JsonSample), "JSON sample")
  if (!json.ok) {
    return json
  }

  const documentation = byId.get(CompilerId.MarkdownDocs)
  const mermaidDiagram = byId.get(CompilerId.MermaidDiagram)

  return {
    ok: true,
    data: {
      sql: sql.output,
      drizzle: drizzle.output,
      json: json.output,
      documentation: documentation?.ok ? documentation.output : undefined,
      mermaidDiagram: mermaidDiagram?.ok ? mermaidDiagram.output : undefined,
    },
  }
}

function requireCompilerOutput(
  result: CompileAllResult["result"] | undefined,
  label: string
): { ok: true; output: string } | { ok: false; error: string } {
  if (!result) {
    return { ok: false, error: `${label} compiler is not registered.` }
  }
  if (!result.ok) {
    return { ok: false, error: `${label} compilation failed: ${result.errors.join(" ")}` }
  }
  return { ok: true, output: result.output }
}
