import { describe, expect, it } from "vitest"

import { postgresSqlCompiler } from "@/lib/compiler/sql/postgres-compiler"
import { buildAst } from "@/lib/compiler/test-helpers"

// Every expected string below was computed by hand from
// lib/compiler/sql's actual rendering logic, then verified against real
// output — not copied from whatever the compiler happened to print.

describe("postgresSqlCompiler", () => {
  it("happy path: renders tables, an index, and a foreign key with actions", () => {
    const ast = buildAst(
      [
        {
          name: "users",
          columns: [
            { name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true, default: { kind: "uuid" } },
            { name: "email", type: "string", nullable: false, unique: true, primaryKey: false },
            {
              name: "role",
              type: "enum",
              nullable: false,
              unique: false,
              primaryKey: false,
              enumValues: ["admin", "member"],
              default: { kind: "literal", value: "member" },
            },
            { name: "created_at", type: "timestamp", nullable: false, unique: false, primaryKey: false, default: { kind: "now" } },
          ],
        },
        {
          name: "posts",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: true, primaryKey: true, default: { kind: "autoincrement" } },
            { name: "author_id", type: "uuid", nullable: false, unique: false, primaryKey: false },
            { name: "title", type: "string", nullable: false, unique: false, primaryKey: false },
          ],
          indexes: [{ name: "idx_posts_title", columns: ["title"] }],
        },
      ],
      [
        {
          sourceTable: "posts",
          sourceColumns: ["author_id"],
          targetTable: "users",
          targetColumns: ["id"],
          onDelete: "cascade",
          onUpdate: "restrict",
        },
      ]
    )

    const result = postgresSqlCompiler.compile(ast)
    expect(result.ok).toBe(true)
    if (!result.ok) return

    expect(result.output).toBe(
      [
        'CREATE TABLE "users" (',
        '  "id" UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,',
        '  "email" VARCHAR(255) NOT NULL UNIQUE,',
        '  "role" TEXT NOT NULL DEFAULT \'member\' CHECK ("role" IN (\'admin\', \'member\')),',
        '  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,',
        '  PRIMARY KEY ("id")',
        ");",
        'CREATE TABLE "posts" (',
        '  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,',
        '  "author_id" UUID NOT NULL,',
        '  "title" VARCHAR(255) NOT NULL,',
        '  PRIMARY KEY ("id")',
        ");",
        "",
        'CREATE INDEX "idx_posts_title" ON "posts" ("title");',
        // Auto-generated to support the FK below — posts.author_id has no
        // explicit index/unique of its own, so this is new since TD-003.
        'CREATE INDEX "idx_posts_author_id" ON "posts" ("author_id");',
        "",
        'ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE RESTRICT;',
      ].join("\n")
    )
  })

  // Prevents accidental non-determinism regressions: an iteration order
  // that silently depended on Map/Set/Object.keys() insertion instead of
  // the AST's own array order, or a stray Math.random()/Date.now() call,
  // would make this fail without changing what the AST "means."
  it("is deterministic: compiling the same AST twice produces byte-identical output", () => {
    const ast = buildAst([
      {
        name: "widgets",
        columns: [{ name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true }],
      },
    ])
    const first = postgresSqlCompiler.compile(ast)
    const second = postgresSqlCompiler.compile(ast)
    expect(first).toEqual(second)
  })

  it("emits no index or foreign-key sections when there are none (no stray blank lines)", () => {
    const ast = buildAst([
      { name: "widgets", columns: [{ name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true }] },
    ])
    const result = postgresSqlCompiler.compile(ast)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.output).toBe('CREATE TABLE "widgets" (\n  "id" UUID NOT NULL UNIQUE,\n  PRIMARY KEY ("id")\n);')
  })

  describe("identifier and literal escaping", () => {
    it("doubles an embedded double quote in a quoted identifier", () => {
      const ast = buildAst([
        {
          name: 'wei"rd',
          columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }],
        },
      ])
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      // toContain, not toBe: this test is scoped to the escaping behavior
      // of one identifier, not the table's full rendering (already pinned
      // exactly by the happy-path and other tests above).
      expect(result.output).toContain('CREATE TABLE "wei""rd" (')
    })

    it("doubles an embedded single quote in a string literal default", () => {
      const ast = buildAst([
        {
          name: "authors",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            {
              name: "name",
              type: "string",
              nullable: false,
              unique: false,
              primaryKey: false,
              default: { kind: "literal", value: "O'Brien" },
            },
          ],
        },
      ])
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toContain("DEFAULT 'O''Brien'")
    })
  })

  describe("literal default rendering by JS type", () => {
    // Parameterized over 5 cases — toContain here checks one DEFAULT
    // clause per case, not the whole statement, which is the right
    // granularity for an it.each covering several distinct value types.
    it.each([
      ["string", "hello", "'hello'"],
      ["number", 42, "42"],
      ["boolean true", true, "TRUE"],
      ["boolean false", false, "FALSE"],
      ["null", null, "NULL"],
    ] as const)("renders a %s literal default as %s", (_label, value, expected) => {
      const ast = buildAst([
        {
          name: "t",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            {
              name: "x",
              type: typeof value === "string" ? "string" : typeof value === "boolean" ? "boolean" : "integer",
              nullable: true,
              unique: false,
              primaryKey: false,
              default: { kind: "literal", value },
            },
          ],
        },
      ])
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toContain(`DEFAULT ${expected}`)
    })
  })

  describe("foreign key actions", () => {
    it.each([
      ["cascade", "CASCADE"],
      ["restrict", "RESTRICT"],
      ["set-null", "SET NULL"],
      ["set-default", "SET DEFAULT"],
      ["no-action", "NO ACTION"],
    ] as const)("maps %s to %s", (astAction, sqlAction) => {
      const ast = buildAst(
        [
          { name: "a", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          {
            name: "b",
            columns: [
              { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "a_id", type: "integer", nullable: false, unique: false, primaryKey: false },
            ],
          },
        ],
        [{ sourceTable: "b", sourceColumns: ["a_id"], targetTable: "a", targetColumns: ["id"], onDelete: astAction }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toContain(`ON DELETE ${sqlAction}`)
    })
  })

  it("auto-generates a foreign key constraint name when the relationship has none", () => {
    const ast = buildAst(
      [
        { name: "a", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
        {
          name: "b",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            { name: "a_id", type: "integer", nullable: false, unique: false, primaryKey: false },
          ],
        },
      ],
      [{ sourceTable: "b", sourceColumns: ["a_id"], targetTable: "a", targetColumns: ["id"] }]
    )
    const result = postgresSqlCompiler.compile(ast)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    // toContain: this fixture is shared in spirit with the declaration-
    // order test below; both target one clause, and the full CREATE TABLE
    // detail is already pinned exactly elsewhere.
    expect(result.output).toContain('ADD CONSTRAINT "fk_b_a_id"')
  })

  it("foreign key ordering does not depend on table declaration order", () => {
    // The source table (b) is declared BEFORE the table it references (a)
    // — the compiler must not need a's declaration first, since FKs are
    // always emitted as ALTER TABLE statements after every CREATE TABLE.
    const ast = buildAst(
      [
        {
          name: "b",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            { name: "a_id", type: "integer", nullable: false, unique: false, primaryKey: false },
          ],
        },
        { name: "a", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
      ],
      [{ sourceTable: "b", sourceColumns: ["a_id"], targetTable: "a", targetColumns: ["id"] }]
    )
    const result = postgresSqlCompiler.compile(ast)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    // toContain: the property under test is "does it resolve regardless
    // of order," not the exact full text — an exact match would just
    // re-assert the auto-generated-name test's content under a different
    // heading.
    expect(result.output).toContain('REFERENCES "a" ("id")')
  })

  describe("table-level constraints and indexes", () => {
    it("renders a table-level UNIQUE constraint", () => {
      const ast = buildAst([
        {
          name: "memberships",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            { name: "user_id", type: "uuid", nullable: false, unique: false, primaryKey: false },
            { name: "org_id", type: "uuid", nullable: false, unique: false, primaryKey: false },
          ],
          constraints: [{ kind: "unique", columns: ["user_id", "org_id"] }],
        },
      ])
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "memberships" (',
          '  "id" INTEGER NOT NULL,',
          '  "user_id" UUID NOT NULL,',
          '  "org_id" UUID NOT NULL,',
          '  PRIMARY KEY ("id"),',
          '  UNIQUE ("user_id", "org_id")',
          ");",
        ].join("\n")
      )
    })

    it("renders a table-level CHECK constraint using the raw expression verbatim", () => {
      // The compiler does not sanitize or re-validate expression content —
      // that's the analyzer's UNSAFE_EXPRESSION check (lib/ast/analyzer.ts),
      // a separate pipeline stage that runs before compilation. This test
      // documents that boundary: the compiler's job is rendering, not
      // validating.
      const ast = buildAst([
        {
          name: "products",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            { name: "price", type: "decimal", nullable: false, unique: false, primaryKey: false },
          ],
          constraints: [{ kind: "check", expression: "price >= 0" }],
        },
      ])
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "products" (',
          '  "id" INTEGER NOT NULL,',
          '  "price" NUMERIC NOT NULL,',
          '  PRIMARY KEY ("id"),',
          "  CHECK (price >= 0)",
          ");",
        ].join("\n")
      )
    })

    it("renders CREATE UNIQUE INDEX when the index is marked unique", () => {
      const ast = buildAst([
        {
          name: "users",
          columns: [
            { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
            { name: "email", type: "string", nullable: false, unique: false, primaryKey: false },
          ],
          indexes: [{ name: "idx_users_email", columns: ["email"], unique: true }],
        },
      ])
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "users" (',
          '  "id" INTEGER NOT NULL,',
          '  "email" VARCHAR(255) NOT NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          "",
          'CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email");',
        ].join("\n")
      )
    })
  })

  describe("regression: self-referencing foreign key", () => {
    it("compiles a self-referencing FK (source table === target table) without error", () => {
      // Matches a real shape observed in production output: a
      // comments.parent_id -> comments.id self-reference (threaded
      // comments) — a real stress case for "FK statements never need
      // topological table ordering," since here source and target are
      // literally the same table.
      const ast = buildAst(
        [
          {
            name: "comments",
            columns: [
              { name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true },
              { name: "parent_id", type: "uuid", nullable: true, unique: false, primaryKey: false },
            ],
          },
        ],
        [{ sourceTable: "comments", sourceColumns: ["parent_id"], targetTable: "comments", targetColumns: ["id"] }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "comments" (',
          '  "id" UUID NOT NULL UNIQUE,',
          '  "parent_id" UUID NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          "",
          'CREATE INDEX "idx_comments_parent_id" ON "comments" ("parent_id");',
          "",
          'ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_parent_id" FOREIGN KEY ("parent_id") REFERENCES "comments" ("id");',
        ].join("\n")
      )
    })
  })

  describe("foreign key indexes (TD-003)", () => {
    it("creates an index for a single-column foreign key", () => {
      const ast = buildAst(
        [
          { name: "users", columns: [{ name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true }] },
          {
            name: "posts",
            columns: [
              { name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true },
              { name: "author_id", type: "uuid", nullable: false, unique: false, primaryKey: false },
            ],
          },
        ],
        [{ sourceTable: "posts", sourceColumns: ["author_id"], targetTable: "users", targetColumns: ["id"] }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "users" (',
          '  "id" UUID NOT NULL UNIQUE,',
          '  PRIMARY KEY ("id")',
          ");",
          'CREATE TABLE "posts" (',
          '  "id" UUID NOT NULL UNIQUE,',
          '  "author_id" UUID NOT NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          "",
          'CREATE INDEX "idx_posts_author_id" ON "posts" ("author_id");',
          "",
          'ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id");',
        ].join("\n")
      )
    })

    it("creates one index per relationship when a table has multiple foreign keys", () => {
      const ast = buildAst(
        [
          { name: "users", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          {
            name: "posts",
            columns: [
              { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "author_id", type: "integer", nullable: false, unique: false, primaryKey: false },
              { name: "editor_id", type: "integer", nullable: true, unique: false, primaryKey: false },
            ],
          },
        ],
        [
          { sourceTable: "posts", sourceColumns: ["author_id"], targetTable: "users", targetColumns: ["id"] },
          { sourceTable: "posts", sourceColumns: ["editor_id"], targetTable: "users", targetColumns: ["id"] },
        ]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      // Index order follows relationship declaration order, same
      // determinism guarantee as every other compiler step.
      expect(result.output).toBe(
        [
          'CREATE TABLE "users" (',
          '  "id" INTEGER NOT NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          'CREATE TABLE "posts" (',
          '  "id" INTEGER NOT NULL,',
          '  "author_id" INTEGER NOT NULL,',
          '  "editor_id" INTEGER NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          "",
          'CREATE INDEX "idx_posts_author_id" ON "posts" ("author_id");',
          'CREATE INDEX "idx_posts_editor_id" ON "posts" ("editor_id");',
          "",
          'ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id");',
          'ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_editor_id" FOREIGN KEY ("editor_id") REFERENCES "users" ("id");',
        ].join("\n")
      )
    })

    it("creates one index covering every column of a composite foreign key", () => {
      const ast = buildAst(
        [
          {
            name: "a",
            columns: [
              { name: "x", type: "integer", nullable: false, unique: false, primaryKey: false },
              { name: "y", type: "integer", nullable: false, unique: false, primaryKey: false },
            ],
          },
          {
            name: "b",
            columns: [
              { name: "x", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "y", type: "integer", nullable: false, unique: false, primaryKey: true },
            ],
            primaryKey: { columns: ["x", "y"] },
          },
        ],
        [{ sourceTable: "a", sourceColumns: ["x", "y"], targetTable: "b", targetColumns: ["x", "y"] }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "a" (',
          '  "x" INTEGER NOT NULL,',
          '  "y" INTEGER NOT NULL',
          ");",
          'CREATE TABLE "b" (',
          '  "x" INTEGER NOT NULL,',
          '  "y" INTEGER NOT NULL,',
          '  PRIMARY KEY ("x", "y")',
          ");",
          "",
          'CREATE INDEX "idx_a_x_y" ON "a" ("x", "y");',
          "",
          'ALTER TABLE "a" ADD CONSTRAINT "fk_a_x_y" FOREIGN KEY ("x", "y") REFERENCES "b" ("x", "y");',
        ].join("\n")
      )
    })

    it("regression: does not duplicate an index when the FK column is already the primary key", () => {
      // A common 1:1 shape: profiles.user_id is both the FK to users.id
      // and profiles' own primary key — already indexed by Postgres via
      // the PRIMARY KEY itself, so no extra index should appear.
      const ast = buildAst(
        [
          { name: "users", columns: [{ name: "id", type: "uuid", nullable: false, unique: true, primaryKey: true }] },
          {
            name: "profiles",
            columns: [
              { name: "user_id", type: "uuid", nullable: false, unique: true, primaryKey: true },
              { name: "bio", type: "text", nullable: true, unique: false, primaryKey: false },
            ],
          },
        ],
        [{ sourceTable: "profiles", sourceColumns: ["user_id"], targetTable: "users", targetColumns: ["id"] }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "users" (',
          '  "id" UUID NOT NULL UNIQUE,',
          '  PRIMARY KEY ("id")',
          ");",
          'CREATE TABLE "profiles" (',
          '  "user_id" UUID NOT NULL UNIQUE,',
          '  "bio" TEXT NULL,',
          '  PRIMARY KEY ("user_id")',
          ");",
          "",
          'ALTER TABLE "profiles" ADD CONSTRAINT "fk_profiles_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
        ].join("\n")
      )
    })

    it("regression: does not duplicate an index when the FK column already has a column-level unique flag", () => {
      const ast = buildAst(
        [
          { name: "users", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          {
            name: "accounts",
            columns: [
              { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "user_id", type: "integer", nullable: false, unique: true, primaryKey: false },
            ],
          },
        ],
        [{ sourceTable: "accounts", sourceColumns: ["user_id"], targetTable: "users", targetColumns: ["id"] }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "users" (',
          '  "id" INTEGER NOT NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          'CREATE TABLE "accounts" (',
          '  "id" INTEGER NOT NULL,',
          '  "user_id" INTEGER NOT NULL UNIQUE,',
          '  PRIMARY KEY ("id")',
          ");",
          "",
          'ALTER TABLE "accounts" ADD CONSTRAINT "fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
        ].join("\n")
      )
    })

    it("regression: does not duplicate an index when the FK columns already match an explicit AST index", () => {
      const ast = buildAst(
        [
          { name: "users", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          {
            name: "posts",
            columns: [
              { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "author_id", type: "integer", nullable: false, unique: false, primaryKey: false },
            ],
            indexes: [{ name: "idx_posts_author_id_custom", columns: ["author_id"] }],
          },
        ],
        [{ sourceTable: "posts", sourceColumns: ["author_id"], targetTable: "users", targetColumns: ["id"] }]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "users" (',
          '  "id" INTEGER NOT NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          'CREATE TABLE "posts" (',
          '  "id" INTEGER NOT NULL,',
          '  "author_id" INTEGER NOT NULL,',
          '  PRIMARY KEY ("id")',
          ");",
          "",
          'CREATE INDEX "idx_posts_author_id_custom" ON "posts" ("author_id");',
          "",
          'ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id");',
        ].join("\n")
      )
    })

    it("regression: does not duplicate an index when the FK columns already match a table-level unique constraint", () => {
      const ast = buildAst(
        [
          {
            name: "orgs",
            columns: [
              { name: "user_ref", type: "integer", nullable: false, unique: false, primaryKey: false },
              { name: "org_ref", type: "integer", nullable: false, unique: false, primaryKey: false },
            ],
          },
          {
            name: "memberships",
            columns: [
              { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "user_id", type: "integer", nullable: false, unique: false, primaryKey: false },
              { name: "org_id", type: "integer", nullable: false, unique: false, primaryKey: false },
            ],
            constraints: [{ kind: "unique", columns: ["user_id", "org_id"] }],
          },
        ],
        [
          {
            sourceTable: "memberships",
            sourceColumns: ["user_id", "org_id"],
            targetTable: "orgs",
            targetColumns: ["user_ref", "org_ref"],
          },
        ]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output).toBe(
        [
          'CREATE TABLE "orgs" (',
          '  "user_ref" INTEGER NOT NULL,',
          '  "org_ref" INTEGER NOT NULL',
          ");",
          'CREATE TABLE "memberships" (',
          '  "id" INTEGER NOT NULL,',
          '  "user_id" INTEGER NOT NULL,',
          '  "org_id" INTEGER NOT NULL,',
          '  PRIMARY KEY ("id"),',
          '  UNIQUE ("user_id", "org_id")',
          ");",
          "",
          'ALTER TABLE "memberships" ADD CONSTRAINT "fk_memberships_user_id_org_id" FOREIGN KEY ("user_id", "org_id") REFERENCES "orgs" ("user_ref", "org_ref");',
        ].join("\n")
      )
    })

    it("regression: two relationships sharing an identical composite FK column set produce only one index", () => {
      // Defensive case, not a claimed realistic schema shape: proves the
      // dedup key is the column set, not the relationship itself, so a
      // table can never end up with two indexes over the exact same columns.
      const ast = buildAst(
        [
          { name: "a", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          { name: "b", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          {
            name: "links",
            columns: [{ name: "a_id", type: "integer", nullable: false, unique: false, primaryKey: false }],
          },
        ],
        [
          { sourceTable: "links", sourceColumns: ["a_id"], targetTable: "a", targetColumns: ["id"] },
          { sourceTable: "links", sourceColumns: ["a_id"], targetTable: "b", targetColumns: ["id"] },
        ]
      )
      const result = postgresSqlCompiler.compile(ast)
      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.output.match(/CREATE INDEX/g) ?? []).toHaveLength(1)
      expect(result.output).toContain('CREATE INDEX "idx_links_a_id" ON "links" ("a_id");')
    })

    it("is deterministic across repeated compiles of a relationship-bearing AST", () => {
      const ast = buildAst(
        [
          { name: "users", columns: [{ name: "id", type: "integer", nullable: false, unique: false, primaryKey: true }] },
          {
            name: "posts",
            columns: [
              { name: "id", type: "integer", nullable: false, unique: false, primaryKey: true },
              { name: "author_id", type: "integer", nullable: false, unique: false, primaryKey: false },
            ],
          },
        ],
        [{ sourceTable: "posts", sourceColumns: ["author_id"], targetTable: "users", targetColumns: ["id"] }]
      )
      expect(postgresSqlCompiler.compile(ast)).toEqual(postgresSqlCompiler.compile(ast))
    })
  })

  it("resolves a table-level composite primary key over column-level flags", () => {
    const ast = buildAst([
      {
        name: "post_tags",
        columns: [
          { name: "post_id", type: "uuid", nullable: false, unique: false, primaryKey: false },
          { name: "tag_id", type: "uuid", nullable: false, unique: false, primaryKey: false },
        ],
        primaryKey: { columns: ["post_id", "tag_id"] },
      },
    ])
    const result = postgresSqlCompiler.compile(ast)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.output).toBe(
      [
        'CREATE TABLE "post_tags" (',
        '  "post_id" UUID NOT NULL,',
        '  "tag_id" UUID NOT NULL,',
        '  PRIMARY KEY ("post_id", "tag_id")',
        ");",
      ].join("\n")
    )
  })
})
