import type { ColumnDefault, ColumnNode } from "@/lib/ast/types"
import { escapeStringLiteral, quoteIdentifier } from "@/lib/compiler/sql/identifiers"
import { mapColumnType } from "@/lib/compiler/sql/type-map"

// Renders one column line for a CREATE TABLE statement:
//   "<name>" <TYPE> [NOT NULL] [GENERATED BY DEFAULT AS IDENTITY | DEFAULT <expr>] [UNIQUE] [CHECK (...)]
export function renderColumnDefinition(column: ColumnNode): string {
  const parts: string[] = [quoteIdentifier(column.name), mapColumnType(column)]

  parts.push(column.nullable ? "NULL" : "NOT NULL")

  if (column.default?.kind === "autoincrement") {
    // Postgres has no bare DEFAULT expression for autoincrement — it's a
    // column constraint (identity column), not a default value.
    parts.push("GENERATED BY DEFAULT AS IDENTITY")
  } else {
    const defaultClause = renderDefaultClause(column.default)
    if (defaultClause) {
      parts.push(defaultClause)
    }
  }

  if (column.unique) {
    parts.push("UNIQUE")
  }

  if (column.type === "enum" && column.enumValues && column.enumValues.length > 0) {
    parts.push(renderEnumCheckClause(column))
  }

  return parts.join(" ")
}

function renderDefaultClause(defaultValue: ColumnDefault | undefined): string | undefined {
  if (!defaultValue) {
    return undefined
  }

  switch (defaultValue.kind) {
    case "literal":
      return `DEFAULT ${renderLiteral(defaultValue.value)}`
    case "now":
      return "DEFAULT CURRENT_TIMESTAMP"
    case "uuid":
      // Requires the pgcrypto extension (available by default on
      // Supabase/most managed Postgres; `create extension if not exists
      // pgcrypto;` otherwise).
      return "DEFAULT gen_random_uuid()"
    case "autoincrement":
      // Handled by the caller as a column constraint, not a DEFAULT clause.
      return undefined
    case "expression":
      // Escape hatch: trusted as already-valid SQL, not re-validated here.
      return `DEFAULT ${defaultValue.expression}`
  }
}

function renderLiteral(value: string | number | boolean | null): string {
  if (value === null) {
    return "NULL"
  }
  if (typeof value === "string") {
    return escapeStringLiteral(value)
  }
  if (typeof value === "boolean") {
    return value ? "TRUE" : "FALSE"
  }
  return String(value)
}

function renderEnumCheckClause(column: ColumnNode): string {
  const values = (column.enumValues ?? []).map(escapeStringLiteral).join(", ")
  return `CHECK (${quoteIdentifier(column.name)} IN (${values}))`
}
