import type { ColumnDefault, ColumnNode, ForeignKeyAction, RelationshipNode } from "@/lib/ast/types"
import { toCamelCase } from "@/lib/compiler/drizzle/identifiers"
import { buildColumnBuilder } from "@/lib/compiler/drizzle/type-map"

export interface SingleColumnForeignKey {
  relationship: RelationshipNode
  targetTableVarName: string
  targetColumnName: string
}

export interface RenderColumnContext {
  primaryKeyColumns: Set<string> // lowercase
  singleColumnForeignKeys: Map<string, SingleColumnForeignKey> // keyed by lowercase source column name
}

export interface RenderedColumn {
  line: string
  comment?: string
  pgCoreImports: string[]
  usesSql: boolean
  usesBytea: boolean
}

// Column chain order mirrors this project's own lib/db/schema.ts
// convention exactly: type -> primaryKey() -> notNull() -> references()
// -> unique() -> default-ish call. A primary-key column never also gets
// an explicit notNull()/unique() call, since primaryKey() already
// implies both — the existing schema.ts never doubles them up either.
export function renderColumnProperty(
  column: ColumnNode,
  context: RenderColumnContext
): RenderedColumn {
  const builder = buildColumnBuilder(column)
  const chain: string[] = [builder.call]

  const isPrimaryKey = context.primaryKeyColumns.has(column.name.toLowerCase())
  if (isPrimaryKey) {
    chain.push("primaryKey()")
  } else if (!column.nullable) {
    chain.push("notNull()")
  }

  let usesSql = false

  const foreignKey = context.singleColumnForeignKeys.get(column.name.toLowerCase())
  if (foreignKey) {
    const options: string[] = []
    if (foreignKey.relationship.onDelete) {
      options.push(`onDelete: ${JSON.stringify(mapForeignKeyAction(foreignKey.relationship.onDelete))}`)
    }
    if (foreignKey.relationship.onUpdate) {
      options.push(`onUpdate: ${JSON.stringify(mapForeignKeyAction(foreignKey.relationship.onUpdate))}`)
    }
    const optionsArg = options.length > 0 ? `, { ${options.join(", ")} }` : ""
    chain.push(
      `references(() => ${foreignKey.targetTableVarName}.${toCamelCase(foreignKey.targetColumnName)}${optionsArg})`
    )
  }

  if (!isPrimaryKey && column.unique) {
    chain.push("unique()")
  }

  if (column.default?.kind === "autoincrement") {
    // Postgres/Drizzle identity columns are a column constraint, not a
    // default expression — same reasoning as the SQL compiler's
    // GENERATED BY DEFAULT AS IDENTITY.
    chain.push("generatedByDefaultAsIdentity()")
  } else {
    const defaultChain = renderDefaultChain(column.default)
    if (defaultChain) {
      chain.push(defaultChain.call)
      usesSql = defaultChain.usesSql
    }
  }

  const comment =
    column.type === "enum" && column.enumValues && column.enumValues.length > 0
      ? `// ${column.name}: one of ${column.enumValues.map((value) => JSON.stringify(value)).join(", ")}`
      : undefined

  return {
    line: `${toCamelCase(column.name)}: ${chain.join(".")},`,
    comment,
    pgCoreImports: builder.pgCoreImports,
    usesSql,
    usesBytea: builder.usesBytea,
  }
}

function renderDefaultChain(
  defaultValue: ColumnDefault | undefined
): { call: string; usesSql: boolean } | undefined {
  if (!defaultValue) {
    return undefined
  }

  switch (defaultValue.kind) {
    case "literal":
      return { call: `default(${renderJsLiteral(defaultValue.value)})`, usesSql: false }
    case "now":
      return { call: "defaultNow()", usesSql: false }
    case "uuid":
      return { call: "defaultRandom()", usesSql: false }
    case "autoincrement":
      // Handled by the caller as generatedByDefaultAsIdentity() instead.
      return undefined
    case "expression":
      return { call: `default(sql\`${defaultValue.expression}\`)`, usesSql: true }
  }
}

function renderJsLiteral(value: string | number | boolean | null): string {
  if (value === null) {
    return "null"
  }
  if (typeof value === "string") {
    return JSON.stringify(value)
  }
  return String(value)
}

// Drizzle's onDelete/onUpdate option strings don't match the AST's
// hyphenated ForeignKeyAction values 1:1 (e.g. "set-null" -> "set null").
function mapForeignKeyAction(action: ForeignKeyAction): string {
  switch (action) {
    case "cascade":
      return "cascade"
    case "restrict":
      return "restrict"
    case "set-null":
      return "set null"
    case "set-default":
      return "set default"
    case "no-action":
      return "no action"
    default: {
      const unreachable: never = action
      throw new Error(`Unhandled foreign key action: ${String(unreachable)}`)
    }
  }
}
