name: Project CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download latest CI artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          RUN_ID=$(gh run list \
            --workflow "Project CI" \
            --branch develop/chirag \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId')

          echo "Run ID : $RUN_ID"

          ARTIFACT_ID=$(gh api \
            repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts \
            --jq '.artifacts[0].id')

          echo "Artifact ID : $ARTIFACT_ID"

          curl -L \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip \
            -o schemacraft-build.zip

      - name: Copy artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "schemacraft-build.zip"
          target: "/tmp"

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |

            sudo mkdir -p /opt/schemacraft-ai

            sudo chown -R $USER:$USER /opt/schemacraft-ai

            cd /opt/schemacraft-ai

            rm -rf *

            unzip -oq /tmp/schemacraft-build.zip

            npm install --omit=dev

            pm2 delete schemacraft-ai || true

            pm2 start npm \
              --name schemacraft-ai \
              -- start

            pm2 save